### ISSUE TITLE
DAMMviz checklist

### ISSUE THREAD

**Issue by AlexisRenchon** [CUPofTEAproject/DAMMmodel.jl#9]
- [x] Rsoil value changing interactively
- [x] vertical and horizontal lines in 2D plots, going from axes to the point, color = Rs 
- [x] same lines as 2D plots on the 3D ax
- [x] lines parallel to axis on 3D plot, equal to current Ts, theta, Rs, + line to dot, colored by value 
- [x] bugfix: porositity when increase slider value #12 fixed by @BernhardAhrens 
- [ ] theta and Rs need to be forced to 3 characters (e.g., 0.00, 1.23, 10.1) 
- [ ] Possible better layout for sliders and params, make a table, maybe use [labelslidergrid!](https://makie.juliaplots.org/v0.15.1/examples/layoutables/slider/)
- [ ] Only substrate limitation and only oxygen limitation on 2D plot, as in Pallandt et al. supplement
- [ ] bugfix: white lines on 3D plot shouldn't be there. Also, surface should be more transparent
